apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuberay
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://ray-project.github.io/kuberay-helm/'
    targetRevision: 1.1.0
    helm:
      valueFiles:
        - values.yaml
    chart: kuberay-operator
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kuberay
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
