apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bitnami/charts.git
    path: bitnami/mlflow
    targetRevision: HEAD
    helm:
      parameters:
        - name: tracking.service.type
          value: ClusterIP
        - name: tracking.auth.enabled
          value: 'false'
        - name: image.tag
          value: 2.16.2-debian-12-r3
        - name: tracking.extraEnvVars[0].name
          value: GUNICORN_CMD_ARGS
        - name: tracking.extraEnvVars[0].value
          value: "--timeout 600 --workers 4 --threads 8"
        - name: tracking.resources.requests.memory
          value: "4Gi"
        - name: tracking.resources.limits.memory
          value: "8Gi"
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
